---
- name: Check current nginx_logfile_exporter version.
  command: "{{ nginx_logfile_exporter_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: nginx_logfile_exporter_version_check

- name: Download and unarchive nginx_logfile_exporter into temporary location.
  unarchive:
    src: "{{ nginx_logfile_exporter_download_url }}"
    dest: /tmp
    remote_src: true
  when: >
    nginx_logfile_exporter_version_check.stdout is not defined
    or nginx_logfile_exporter_version not in nginx_logfile_exporter_version_check.stdout
  register: nginx_logfile_exporter_download_check

- name: Move nginx_logfile_exporter binary into place.
  copy:
    src: "/tmp/prometheus-nginxlog-exporter"
    dest: "{{ nginx_logfile_exporter_bin_path }}"
    mode: 0755
    remote_src: true
  notify: restart nginx_logfile_exporter
  when: nginx_logfile_exporter_download_check is success

- name: Move config into place.
  copy:
    src: files/nginx_logfile_exporter.hcl
    dest: /etc/nginx_logfile_exporter.hcl
    mode: 0644
  when: nginx_logfile_exporter_download_check is success

- name: Create nginx_logfile_exporter user.
  user:
    name: nginx_logfile_exporter
    shell: /sbin/nologin
    state: present

- name: adding nginx_logfile_exporter to group adm
  user:
    name: nginx_logfile_exporter
    groups: adm
    append: yes

- name: Copy the nginx_logfile_exporter systemd unit file.
  template:
    src: nginx_logfile_exporter.service.j2
    dest: /etc/systemd/system/nginx_logfile_exporter.service
  register: nginx_logfile_exporter_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart nginx_logfile_exporter
  when: nginx_logfile_exporter_service is changed

- name: Ensure nginx_logfile_exporter is running and enabled at boot.
  service:
    name: nginx_logfile_exporter
    state: "{{ nginx_logfile_exporter_state }}"
    enabled: "{{ nginx_logfile_exporter_enabled }}"

- name: Verify nginx_logfile_exporter is responding to requests.
  uri:
    url: http://localhost:4040/
    return_content: true
  register: metrics_output
  failed_when: "'404 page' not in metrics_output.content"
